spring:
  redis:
    host: 127.0.0.1
    password: foobared
    port: 6379
    database: 0
    lettuce:
      pool:
        min-idle: 8
        max-active: 32
        max-idle: 16

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3307/ms?useUnicode=true&characerEncoding=utf-8&useSSL=false&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    hikari:
      connection-test-query: SELECT 1
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 60000
      connection-timeout: 30000
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: LEGACYHTML5 # 用非严格的 HTML
  web:
    resources:
      static-locations: classpath:/templates/static/

  jackson:
    local-date-time-format: yyyy/MM/dd HH:mm:ss
    local-date-format: yyyy/MM/dd
    local-time-format: HH:mm:ss

mybatis-plus:
  configuration:
    default-fetch-size: 100
    default-statement-timeout: 3000
    map-underscore-to-camel-case: true
  type-aliases-package: com.lybb.ms.entity
  mapper-locations: classpath:/mapper/**/*.xml